# Static analysis configuration for Cheetah Driver & Picker Mobile App
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    constant_identifier_names: false
