name: iOS Simulator Build for LambdaTest

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Simulator App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Pod Install
        working-directory: ios
        run: pod install

      - name: Build iOS for Simulator
        run: flutter build ios --simulator

      - name: Build iOS .ipa for Real Devices & Testing
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r CheetahDriver.ipa Payload

      - name: Zip the .app for LambdaTest Simulators
        working-directory: build/ios/iphonesimulator
        run: zip -r Runner.app.zip Runner.app

      - name: Upload iOS Build Artifacts (.ipa and .app.zip)
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-files
          path: |
            build/ios/iphonesimulator/Runner.app.zip
            build/ios/iphoneos/CheetahDriver.ipa
          retention-days: 5
